// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.donation.eoy.version.viewed", 1);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1685191120);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1685191240);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1685191149);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1685191093);
user_pref("browser.search.region", "ES");
user_pref("calendar.caldav.googleResync", 1685191091);
user_pref("calendar.list.sortOrder", "2223d88a-6344-4f0c-9af8-0bd6421ce8f7");
user_pref("calendar.registry.2223d88a-6344-4f0c-9af8-0bd6421ce8f7.calendar-main-default", true);
user_pref("calendar.registry.2223d88a-6344-4f0c-9af8-0bd6421ce8f7.calendar-main-in-composite", true);
user_pref("calendar.registry.2223d88a-6344-4f0c-9af8-0bd6421ce8f7.disabled", true);
user_pref("calendar.registry.2223d88a-6344-4f0c-9af8-0bd6421ce8f7.name", "Casa");
user_pref("calendar.registry.2223d88a-6344-4f0c-9af8-0bd6421ce8f7.type", "storage");
user_pref("calendar.registry.2223d88a-6344-4f0c-9af8-0bd6421ce8f7.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Europe/Madrid");
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1685191100833");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1686994549);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230503190012");
user_pref("extensions.lastAppVersion", "102.11.0");
user_pref("extensions.lastPlatformVersion", "102.11.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"1b0d9417-cdbf-443a-9ab7-18b5c055c4ea\",\"google@search.mozilla.org\":\"57a0337d-5464-4f78-9f0f-b0a615614a42\",\"ddg@search.mozilla.org\":\"b90c439a-46f9-4840-a9a1-473f70789103\",\"wikipedia@search.mozilla.org\":\"05fba42c-c99f-4e3c-a0fb-36389d5f901d\",\"bing@search.mozilla.org\":\"2e64090a-5821-4ba0-a580-6d6de06c8f3a\",\"drae@search.mozilla.org\":\"dfe47c11-e67d-4a6e-9810-30d2011c3bd6\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1685191270);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 34);
user_pref("mailnews.database.global.datastore.id", "cda456d8-1df6-4f9a-97a4-f7d41e6e8ea");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "102.11.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Importante");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Trabajo");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "Por hacer");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Más tarde");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1685191270);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("services.settings.clock_skew_seconds", -8881);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1685200120);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1685200120);
user_pref("services.settings.thunderbird.search-config.last_check", 1685200120);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1685200120);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1685191270);
user_pref("toolkit.telemetry.cachedClientID", "00809961-53c4-47d5-9139-75d373bdbf68");
user_pref("toolkit.telemetry.previousBuildID", "20230503190012");
